### PR TITLE
fix code lens scope for error hotspot Closes #2541

### LINKED ISSUE #2541: Clicking error hotspot issue selects an 'empty' scope leading to an illegal state
STR:
Open the Petclinic app
Click on the errors tab in the UI repeatedly
Check the error controller code, to see an `error hotspot` issue lens.
Click on the lens - UI will be in an illegal state.

Expected behavior:
Clicking the lens should select the relevant span scope if we know it (based on the method, discovery etc.) if we don't know the span, clicking the lens should show a message "No asset found for current method"

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU1DQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe74ee083b58a5fbf5640dcaf579ebc4a84e1037/Screen%20Recording%202024-09-25%20at%2011.35.00%E2%80%AFPM.mov)

### PR DESCRIPTION
**Pull request by shalom938**

### CODE REVIEW

File: model/src/main/kotlin/org/digma/intellij/plugin/model/rest/codelens/Decorator.kt [hunk 1]
```diff
@@ -12,11 +13,24 @@ data class Decorator
...
     val codeObjectId: String,
+    val spanCodeObjectId: String?,
     val importance: InsightImportance
-)
+) {
+    @JsonIgnore
+    fun getScopeCodeObjectId(): String? {
+        return if (codeObjectId.startsWith("span:")) {
+            codeObjectId
+        } else if (spanCodeObjectId != null && spanCodeObjectId.startsWith("span:")) {
```
Comment (shaykeren) [inline model/src/main/kotlin/org/digma/intellij/plugin/model/rest/codelens/Decorator.kt:30]: always true : spanCodeObjectId.startsWith("span:")

**Review by shaykeren — APPROVED** [review]
