### PR TITLE
Bug fix/Navigation for JAX-RS even if backend does not have code object

### LINKED ISSUE #1039: Bug/JAX-RS code navigation when backend does not have code object
following issue #1019 and PR #1032 - the JAX-RS still does not support code navigation

### PR DESCRIPTION
**Pull request by arik-dig**
fixes #1039 

part of solution encountered the problem where `AllClassesSearch.search` doesn't work.
follow this issue
https://youtrack.jetbrains.com/issue/IDEA-328048

### CODE REVIEW

File: java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/JavaPsiUtils.kt [hunk 1]
```diff
@@ -42,14 +43,6 @@ class JavaPsiUtils {
             }
         }
 
-        @JvmStatic
-        @NotNull
-        fun getClassesWithin(psiFile: PsiFile): List<PsiClass> {
-            //it must be a PsiJavaFile so casting should be ok
-            val psiJavaFile = psiFile as PsiJavaFile
-            return psiJavaFile.classes.asList()
-        }
```
Comment (shalom938) [inline java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/JavaPsiUtils.kt:51]: if must be PsiJavaFile then the argument can be PsiJavaFile . this method will fails if sent another file type.

File: java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java [hunk 2]
```diff
@@ -97,6 +101,33 @@ private void buildEndpointAnnotations(@NotNull SearchScope searchScope) {
...
+    protected PsiFile getPsiFile(@NotNull VirtualFile virtualFile) {
+        final PsiFile psiFile;
+        try {
+            psiFile = PsiUtils.uriToPsiFile(virtualFile.getUrl(), project);
+        } catch (PsiFileNotFountException e) {
+            // very unlikely
+            return null;
+        }
+        return psiFile;
+    }
```
Comment (shalom938) [inline java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java:114]: That is not the way to get PsiFile from VirtualFile.
the way is:
PsiFile psiFile = PsiManager.getInstance(project).findFile(virtualFile);

PsiUtils.uriToPsiFile is for very specific use cases when we really only have a url to a file

File: java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java [hunk 3]
```diff
@@ -97,6 +101,33 @@ private void buildEndpointAnnotations(@NotNull SearchScope searchScope) {
...
+
+    private void buildEndpointAnnotations(@NotNull VirtualFile virtualFile) {
+        final PsiFile psiFile = getPsiFile(virtualFile);
+        if (psiFile == null) return;
+
```
Comment (shalom938) [inline java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java:119]: if psiFile is null then something is wrong with the whole logic.
the logic of discovery should only start when we have a valid java psi file.

File: java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java [hunk 4]
```diff
@@ -140,7 +171,7 @@ public void fileChanged(VirtualFile virtualFile) {
                     //if file moved then removeDocumentEndpoints will not remove anything but building endpoint locations will
                     // override the entries anyway
                     removeDocumentEndpoint(virtualFile);
-                    buildEndpointAnnotations(GlobalSearchScope.fileScope(project, virtualFile));
+                    buildEndpointAnnotations(virtualFile);
                 } finally {
                     buildLock.unlock();
```
Comment (shalom938) [inline java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java:176]: need to check if buildLock.isHeldByCurrentThread

File: java/src/main/java/org/digma/intellij/plugin/idea/psi/java/AbsJaxrsFramework.java [hunk 5]
```diff
@@ -114,59 +112,102 @@ private boolean isJaxRsHttpRelevant() {
         return jaxrsPathAnnotationClass != null;
```
Comment (shalom938) [inline java/src/main/java/org/digma/intellij/plugin/idea/psi/java/AbsJaxrsFramework.java:112]: is AbsJaxrsFramework shortcut for AbstractJaxrsFramework ? isn't that confusing with abs functions? IMP shortcut for Abstract is not clear.

File: java/src/main/java/org/digma/intellij/plugin/idea/psi/java/IEndpointDiscovery.java [hunk 6]
```diff
@@ -15,8 +15,13 @@ public interface IEndpointDiscovery {
```
Comment (shalom938) [inline java/src/main/java/org/digma/intellij/plugin/idea/psi/java/IEndpointDiscovery.java:15]: We don't use I as prefix of interfaces names? and its not common in java. why start a new convention?

File: java/src/main/java/org/digma/intellij/plugin/idea/psi/java/AbsJaxrsFramework.java [hunk 7]
```diff
@@ -114,59 +112,102 @@ private boolean isJaxRsHttpRelevant() {
...
+            return Collections.emptyList();
         }
 
-        var psiFacade = JavaPsiFacade.getInstance(project);
-        final PsiClass appPathAnnotationClass = psiFacade.findClass(getApplicationPathAnnotationClassFqn(), GlobalSearchScope.allScope(project));
-
-        List<PsiClass> allClassesInFile = JavaPsiUtils.getClassesWithin(psiFile);
-        for (PsiClass currClass : allClassesInFile) {
-            final PsiAnnotation controllerPathAnnotation = JavaPsiUtils.findNearestAnnotation(currClass, JAX_RS_PATH_ANNOTATION_STR());
+        Collection<PsiClass> allClassesInFile = PsiTreeUtil.findChildrenOfType(psiFile, PsiClass.class);
```
Comment (shalom938) [inline java/src/main/java/org/digma/intellij/plugin/idea/psi/java/AbsJaxrsFramework.java:126]: direct psi api calls have better performance then finders.
so psiFile.getClasses is better the PsiTreeUtil.findChildrenOfType

File: java/src/main/java/org/digma/intellij/plugin/idea/psi/java/AbsJaxrsFramework.java [hunk 8]
```diff
@@ -114,59 +112,102 @@ private boolean isJaxRsHttpRelevant() {
...
 
-                for (JavaAnnotation currExpectedAnnotation : httpMethodsAnnotations) {
-                    PsiAnnotation httpMethodAnnotation = JavaPsiUtils.findNearestAnnotation(currPsiMethod, currExpectedAnnotation.getClassNameFqn());
-                    if (httpMethodAnnotation == null) {
-                        continue; // skipping since could not find annotation of HTTP Method, such as @GET
-                    }
-                    String endpointSuffixUri = combinePaths(controllerPathAnnotation, methodPathAnnotation);
+    @Override
+    public List<EndpointInfo> lookForEndpoints(@NotNull SearchScope searchScope) {
+        lateInit();
```
Comment (shalom938) [inline java/src/main/java/org/digma/intellij/plugin/idea/psi/java/AbsJaxrsFramework.java:148]: what is the purpose of lateInit ? why not do it in the constructor?

**Review by shalom938 — CHANGES_REQUESTED** [review]

**Review by shalom938 — CHANGES_REQUESTED** [review]

File: java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/JavaPsiUtils.kt (hunk 1 above)
Comment (arik-dig) [reply java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/JavaPsiUtils.kt:51]: this method been removed :-)

File: java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java (hunk 3 above)
Comment (arik-dig) [reply java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java:119]: what do you suggest, fail fast, and throw exception?

File: java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java (hunk 4 above)
Comment (arik-dig) [reply java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java:176]: and if not?
can you suggest the code block?

File: java/src/main/java/org/digma/intellij/plugin/idea/psi/java/AbsJaxrsFramework.java (hunk 5 above)
Comment (arik-dig) [reply java/src/main/java/org/digma/intellij/plugin/idea/psi/java/AbsJaxrsFramework.java:112]: i'll rename

File: java/src/main/java/org/digma/intellij/plugin/idea/psi/java/AbsJaxrsFramework.java [hunk 9]
```diff
@@ -114,59 +112,102 @@ private boolean isJaxRsHttpRelevant() {
...
     }
 
+    /**
+     * Overriding since have different logic,
+     * in this impl searching for classes/methods in file and see if they inherit from super classes which declare on @PATH annotations.
+     */
     @Override
-    public void endpointDiscovery(@NotNull PsiFile psiFile, @NotNull DocumentInfo documentInfo) {
+    public List<EndpointInfo> lookForEndpoints(@NotNull PsiFile psiFile) {
         lateInit();
```
[the remark this answers is not in the document]
Comment (arik-dig) [reply java/src/main/java/org/digma/intellij/plugin/idea/psi/java/AbsJaxrsFramework.java:121]: constructor might be too soon

File: java/src/main/java/org/digma/intellij/plugin/idea/psi/java/AbsJaxrsFramework.java (hunk 7 above)
Comment (arik-dig) [reply java/src/main/java/org/digma/intellij/plugin/idea/psi/java/AbsJaxrsFramework.java:126]: PsiJavaFile.getClasses was not working well

File: java/src/main/java/org/digma/intellij/plugin/idea/psi/java/AbsJaxrsFramework.java (hunk 8 above)
Comment (arik-dig) [reply java/src/main/java/org/digma/intellij/plugin/idea/psi/java/AbsJaxrsFramework.java:148]: constructor might be too early

File: java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java [hunk 10]
```diff
@@ -97,6 +101,33 @@ private void buildEndpointAnnotations(@NotNull SearchScope searchScope) {
         });
     }
 
+    @Nullable
+    protected PsiFile getPsiFile(@NotNull VirtualFile virtualFile) {
+        final PsiFile psiFile;
+        try {
+            psiFile = PsiUtils.uriToPsiFile(virtualFile.getUrl(), project);
```
[the remark this answers is not in the document]
Comment (arik-dig) [reply java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java:108]: looking

File: java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/JavaPsiUtils.kt (hunk 1 above)
Comment (shalom938) [reply java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/JavaPsiUtils.kt:51]: ok, sorry

File: java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (arik-dig) [reply java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java]: ok fixed

File: java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java (hunk 3 above)
Comment (shalom938) [reply java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java:105]: OK, I agree its unlikely.  maybe just a log message so we have an idea when that happens. it may happen on corrupted index of if the file was deleted.

File: java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java (hunk 4 above)
Comment (shalom938) [reply java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java:162]: if (buildLock.isHeldByCurrentThread) {
        lock.unlock()
}

we had exceptions in the past because of that, its just good practice. and if there is code we don't check that then we should.

File: java/src/main/java/org/digma/intellij/plugin/idea/psi/java/AbsJaxrsFramework.java (hunk 7 above)
Comment (shalom938) [reply java/src/main/java/org/digma/intellij/plugin/idea/psi/java/AbsJaxrsFramework.java:126]: That is strange. but i can't argue. usually PsiJavaFile.getClasses works well unless index is not ready or corrupted.

File: java/src/main/java/org/digma/intellij/plugin/idea/psi/java/AbsJaxrsFramework.java (hunk 8 above)
Comment (shalom938) [reply java/src/main/java/org/digma/intellij/plugin/idea/psi/java/AbsJaxrsFramework.java:148]: Yes, and i think i know why. because when constructing the instance indexes are not ready yet and the instance requires indexes to be ready because its using JavaPsiFacade search methods.
It starts because all the framework classes are constructed as members on JavaLanguageService which is constructed before indexes are ready. JavaLanguageService does not require indexes to be ready.

I think that all the framework classes don't need to be instances of JavaLanguageService, they can be constructed when needed and usually its in a stage when indexes are ready. their construction is not heavy so an instance can be constructed every time its needed.

fro example JavaEndpointNavigationProvider.buildEndpointAnnotations is called in smart mode so indexes are ready, and you can construct the EndpointDiscovery only then and avoid the lateInit.
or it can all be static methods like JavaSpanDiscoveryUtils for example.

as i see all these framework classes don't have state, they do have members , for example 'PsiClass controllerAnnotationClass'  or 'PsiClass jaxrsPathAnnotationClass'
but this is also not the best, jetbrains recommend not keeping instances of PSI elements as members because PSI elements may be disposed and new ones built. you never know when this PSI element becomes invalid because of reparse.  if you really need to keep an reference to PSI elements you should keep it in SmartPsiElementPointer. 

So i think all the framework classes can be static methods. search for annotations or classes when you need them, make sure its always run in smart mode with read action

**Review by shalom938 — APPROVED** [review]

File: java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java (hunk 4 above)
Comment (arik-dig) [reply java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java:162]: 1) its out of scope of this PR
2) do you have links to issue(s)?

Comment (shalom938) [reply java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java:162]: there are no issues but we had exceptions and in most places we do this check before unlock
