### PR TITLE
Micronaut discovery Closes #1581 Closes #1589

### LINKED ISSUE #1581: micronaut - Support micronaut client side discovery
See annotation:

### LINKED ISSUE #1589: wrong endpoint id in some micronaut versions
when our micronaut discovery was developed there was a bug in micronaut tracing that they added GET GET to the endpoint id and our discovery did the same. 
probably they fixed it and in later micronaut versions our client discovery doesn't match.

see this bug Arik opened
https://github.com/micronaut-projects/micronaut-tracing/issues/219#top

so it means that starting from some version of micronaut tracing the endpoint id that we generate is wrong because it includes GET GET. and the plugin will not work correctly.
we probably need to understand in which library was the fix and which version and create the endpoint id accordingly.

related issue
https://github.com/digma-ai/digma-intellij-plugin/issues/1581

### PR DESCRIPTION
**Pull request by shalom938**

### CODE REVIEW

File: jvm-common/src/main/java/org/digma/intellij/plugin/idea/psi/discovery/endpoint/MicronautFramework.java [hunk 1]
```diff
@@ -154,12 +160,59 @@ protected static String createHttpEndpointCodeObjectId(PsiMethod psiMethod, Java
...
+            //fix for micronaut 3.7.6 and bellow where the endpoint id should contain double GET GET
+            endpointId = endpointId + httpMethodUcase + " - " + EndpointDiscoveryUtils.combineUri(endpointUriPrefix, endpointUriSuffix);
+        } else {
+            endpointId = endpointId + EndpointDiscoveryUtils.combineUri(endpointUriPrefix, endpointUriSuffix);
+        }
+
+        return endpointId;
+    }
+
+    private boolean isMicronaut376OrBellow(PsiMethod psiMethod) {
```
Comment (arik-dig) [inline jvm-common/src/main/java/org/digma/intellij/plugin/idea/psi/discovery/endpoint/MicronautFramework.java:178]:
```suggestion
    private boolean isMicronaut3dot7dot6OrBellow(PsiMethod psiMethod) {
```

File: jvm-common/src/main/java/org/digma/intellij/plugin/idea/psi/discovery/endpoint/MicronautFramework.java [hunk 2]
```diff
@@ -154,12 +160,59 @@ protected static String createHttpEndpointCodeObjectId(PsiMethod psiMethod, Java
...
+
+        var micronautLib = Arrays.stream(orderEntries)
+                .filter(orderEntry -> orderEntry instanceof LibraryOrderEntry &&
+                        ((LibraryOrderEntry) orderEntry).getLibraryName() != null &&
+                        ((LibraryOrderEntry) orderEntry).getLibraryName().contains("io.micronaut:micronaut-core"))
+                .findFirst().orElse(null);
+
+        if (micronautLib == null) {
+            return false;
+        }
```
Comment (arik-dig) [inline jvm-common/src/main/java/org/digma/intellij/plugin/idea/psi/discovery/endpoint/MicronautFramework.java:196]: we already have `ModuleMetadata` - maybe use it instead of copy-paste the code?

**Review by arik-dig — APPROVED** [review]
